### ISSUE TITLE
403 Forbidden when using CoinMetricsDataExporter

### ISSUE THREAD

**Issue by potter-bul** [coinmetrics/api-client-python#11]
I keep getting 403 when trying to use the Flat Files Exporter. I do not get it when using the json downloader. I have an api_key.

I followed the documentation at the bottom of: https://coinmetrics.github.io/api-client-python/site/FlatFilesExport.html

Here are the response variables:
`{'_content': b'<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor="white">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>openresty/1.13.6.2</center>\r\n</body>\r\n</html>\r\n', '_content_consumed': True, '_next': None, 'status_code': 403, 'headers': {'Date': 'Wed, 25 Jan 2023 17:37:26 GMT', 'Content-Type': 'text/html', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '78f2c6d6286f27ae-SEA', 'Content-Encoding': 'gzip', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'}, 'raw': <urllib3.response.HTTPResponse object at 0x10b22b2b0>, 'url': 'https://files.coinmetrics.io/api/market-trades-spot', 'encoding': 'ISO-8859-1', 'history': [], 'reason': 'Forbidden', 'cookies': <RequestsCookieJar[]>, 'elapsed': datetime.timedelta(microseconds=845653), 'request': <PreparedRequest [GET]>, 'connection': <requests.adapters.HTTPAdapter object at 0x10b22a620>}
`
I get the same when I run it through the command line.

**Comment by ianmclaughlin-cm** [comment]
Hi @potter-bul, thanks for raising this issue. It wasn't documented well in this repo, but the flat files server is actually a separate Coin Metrics production from the API. I just released a new version of the API and documentation with a clearer error message and explanation for this. If you would like access to the flat files server, please reach to the Coin Metrics Customer Support team in order to see about this. Besides that, if you are trying to query a large amount of data just using the API, but not sure the best way to do that, I am happy to help point you in the right direction.
